---
title: "Simulated RCT--read the data"
author: "Harold Pollack"
date: "3/5/2021"
output:
  html_document: default
  word_document: default
---


```{r setup, include=FALSE}
library("dplyr")
library("ivreg")
library("Hmisc")
library("ggplot2")
library("hrbrthemes")
library("tidyr")
library("viridis")
library("boot")
knitr::opts_chunk$set(echo = TRUE)
```



```{r, read RCT data, echo=FALSE}
#
#  dest_path is the directory where you have placed the csv file
#
dest_path<-"/Users/haroldpollack/documents/SSA_456_2021/"
dest_filename<-"tutoring_RCT.csv"
complete_file_name<-paste0(dest_path,dest_filename)
v_data_frame<-read.csv(complete_file_name)
#str(v_data_frame)
paste("Check baseline balance of urbanicity.")
t.test(urban ~ Z, data = v_data_frame)
paste("Check baseline balance of gender.")
t.test(woman ~ Z, data = v_data_frame)

#str(v_data_frame)
#describe(v_data_frame)
paste("Regression analysis of test scores as a function of gender and urbanicity alone.")
model_score_nodose<-lm(score ~ woman+urban, data = v_data_frame)
summary(model_score_nodose)

paste("Regression analysis of tutoring dose as a function of gender and urbanicity alone.")
model_dose_noZ<-lm(dose ~ woman+urban+Z, data = v_data_frame)
summary(model_dose_noZ)



paste("Regression analysis of tutoring dose as a function of gender, urbanicity, and treatment group Z.")
model_dose<-lm(dose ~ woman+urban+Z, data = v_data_frame)
summary(model_dose)

paste("Regression analysis of test scores as a function of gender, urbanicity, and tutoring dose.")
model_score<-lm(score ~ dose+woman+urban, data = v_data_frame)
summary(model_score)

paste("Regression analysis of test scores as a function of gender, urbanicity, and treatment group Z.")
model_score_Z_and_confounders<-lm(score ~ woman+urban+Z, data = v_data_frame)
summary(model_score_Z_and_confounders)

paste("Regression analysis of test scores as a function of treatment group Z alone.")
model_score_Z_only<-lm(score ~ Z, data = v_data_frame)
summary(model_score_Z_only)

v1<- aggregate(x = v_data_frame$dose,    
          by = list(v_data_frame$Z),        
          FUN = mean)    

v2<- aggregate(x = v_data_frame$score,     
          by = list(v_data_frame$Z),  
          FUN = mean)                 
paste("Wald estimator of the value of tutoring (per dose)",(v2[2,2]-v2[1,2])/(v1[2,2]-v1[1,2]))

paste("Instrumental variables analysis of test scores as a function of gender, urbanicity, and tutoring dose.")
ivreg_rct = ivreg(score~dose+woman+urban | woman+urban+Z,data=v_data_frame)
summary(ivreg_rct,diagnostics=TRUE)
#table(v_data_frame$woman)

#
#   Reduced form
#
paste("Regression analysis of tutoring dose as a function of treatment group Z.")
model_dose_Z<-lm(dose ~ Z, data = v_data_frame)
summary(model_dose_Z)

paste("Regression analysis of test scores as a function of treatment group Z.")
model_score_Z<-lm(score ~ Z, data = v_data_frame)
summary(model_score_Z)

mean_wald <- function (v_data_frame){
    v1<- aggregate(x = v_data_frame$dose,    
                   by = list(v_data_frame$Z),        
                   FUN = mean)    
    
    v2<- aggregate(x = v_data_frame$score,     
                   by = list(v_data_frame$Z),  
                   FUN = mean)   
    d<-(v2[2,2]-v2[1,2])/(v1[2,2]-v1[1,2])
    return (d)   }
#bo <- boot(data=v_data_frame, statistic=mean_wald, R=1000)
#boot.ci(bo, conf=0.95)

# Bootstrap 95% CI for Wald estimator
# function to obtain R-Squared from the data
#
# number of bootstrap replicates
#
B <- 1000
#

Wald_ratio <- function(data, indices) {
  d <- data[indices,] # allows boot to select sample
   v1<- aggregate(x = d$dose,    
                   by = list(d$Z),        
                   FUN = mean)    
    
    v2<- aggregate(x = d$score,     
                   by = list(d$Z),  
                   FUN = mean)   
    d<-(v2[2,2]-v2[1,2])/(v1[2,2]-v1[1,2])
  return(d)
}
#
# bootstrapping with B replications
#
results <- boot(data=v_data_frame, statistic=Wald_ratio,
   R=B)
#results
#plot(results)
#str(results)
#head(results)
bs_estimates<-data_frame(results$t)
#summary(bs_estimates)
#str(bs_estimates)
#
# get 95% confidence interval
#boot.ci(results)
#
hist(bs_estimates,breaks=20,main="Bootstrap histogram of Wald Estimator",xlab="Trial estimate")
LB<-round(0.025*B)
UB<-round(0.975*B)
bs_estimates<-bs_estimates[order(results$t),]
paste0("95% confidence interval of Wald estimate of TOT treatment effect: (", bs_estimates[LB,]," , ",bs_estimates[UB,],")") 


```

densities

```{r, densities, echo=FALSE}
v_data_frame$fwoman <- factor(v_data_frame$woman,levels=c(0,1),labels=c("other","women"))
v_data_frame$furban <- factor(v_data_frame$urban,levels=c(0,1),labels=c("other","urban"))
v_data_frame$fZ <- factor(v_data_frame$Z,levels=c(0,1),labels=c("Control","Treatment"))

p1 <- ggplot(data=v_data_frame, aes(x=dose, group=fwoman, fill=fwoman)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p1 + ggtitle("Tutoring dose by gender") +
  xlab("Tutoring dose") + ylab("Density")

p2 <- ggplot(data=v_data_frame, aes(x=dose, group=furban, fill=furban)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p2 + ggtitle("Tutoring dose by Urbanicity") +
  xlab("Tutoring dose") + ylab("Density")

p3 <- ggplot(data=v_data_frame, aes(x=score, group=fwoman, fill=fwoman)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p3 + ggtitle("Test score by gender") +
  xlab("Test score") + ylab("Density")

p4 <- ggplot(data=v_data_frame, aes(x=score, group=furban, fill=furban)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p4 + ggtitle("Test score by Urbanicity") +
  xlab("Test score") + ylab("Density")


p5 <- ggplot(data=v_data_frame, aes(x=dose, group=fZ, fill=fZ)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p5 + ggtitle("Tutoring dose by Treatment assignment") +
  xlab("Tutoring dose") + ylab("Density")

p6 <- ggplot(data=v_data_frame, aes(x=score, group=fZ, fill=fZ)) +
    geom_density(adjust=1.5, alpha=.4) +
    theme_ipsum()
p6 + ggtitle("Test score by Treatment assignment") +
  xlab("Test score") + ylab("Density")




```